# Generated by Django 3.2.18 on 2023-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200726_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbElections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('moderators', models.CharField(blank=True, max_length=255, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_elections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbGuarantees',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('election_id', models.IntegerField(blank=True, null=True)),
                ('civil_id', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('work', models.CharField(blank=True, max_length=255, null=True)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('guarantee', models.IntegerField(blank=True, null=True)),
                ('attended', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_guarantees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('parentid', models.IntegerField(blank=True, db_column='parentId', null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbPermissionMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionid', models.IntegerField(blank=True, db_column='permissionId', null=True)),
                ('menuid', models.IntegerField(blank=True, db_column='menuId', null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_permissionmenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbSorting',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_sorting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUserRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('permissionid', models.IntegerField(blank=True, db_column='permissionId', null=True)),
                ('parentid', models.IntegerField(blank=True, db_column='parentId', null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_user_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('cid', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('election_option', models.CharField(blank=True, max_length=255, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUsersRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('permissionid', models.IntegerField(blank=True, db_column='permissionId', null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_users_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbVoters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.IntegerField(blank=True, null=True)),
                ('civil_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_voters',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.DeleteModel(
            name='cards',
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
