# Generated by Django 3.2.18 on 2023-04-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20230410_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbTeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField(blank=True, null=True)),
                ('teamuser_id', models.IntegerField(blank=True, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('create_by', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_team_members',
                'managed': False,
            },
        ),
    ]
